CREATE TABLE IF NOT EXISTS users(
    id BIGSERIAL PRIMARY KEY,
    email VARCHAR NULL DEFAULT null UNIQUE,
    phone VARCHAR NULL DEFAULT null UNIQUE,
    "name" VARCHAR NOT NULL,
    "password" VARCHAR NOT NULL,
    image_url VARCHAR NULL DEFAULT null,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes
CREATE INDEX phone ON users (phone);
CREATE INDEX email ON users (email);
